site_name: Actividades
dev_addr: 127.0.0.1:8001
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Individuales:
        - Actividad 1: individual/Actividad-01.md
        - Actividad 2: individual/Actividad-02.md
        - Actividad 3: individual/Actividad-03.md
    - Bonus:
        - Bonus 1: bonus/Bonus-01.md
        - Bonus 2: bonus/Bonus-02.md 
    - Colaborativas:
        - Actividad 1: todo.md
copyright: ©SSRS
site_author: SSRS
